
[package]
name = "ffxiv-excel-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
physis.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"
camino = "1"
anyhow = "1.0.100"
